---
- name: registry
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: create auth directory
      become: yes
      file:
        path: /opt/registry/auth
        state: directory
        mode: 0755

    - name: create htpassword if not exist
      become: yes
      shell: >
        docker run
        --entrypoint htpasswd
        --rm
        registry:2
        -Bbn admin wapwap12
        > /opt/registry/auth/htpasswd
      args:
        chdir: /opt/registry/auth
        creates: htpasswd

    - name: create images directory
      become: yes
      file:
        path: /opt/registry/data
        state: directory
        mode: 0755