apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: test:latest
        name: test
        imagePullPolicy: Never
        ports:
         - name: http
           containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app: test
spec:
  ports:
  - nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80    
  selector:
    app: test
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}               