---
- name: afg
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: create project
      file:
        path: /home/vagrant/project
        state: directory
        mode: 0755

    # - name: Update common packages
    #   become: yes
    #   apt:
    #     name:
    #       - apt-transport-https
    #     update_cache: yes
    #   tags: update

    # - name: clone jupyterlab-docker from github
    #   git:
    #     repo: 'https://github.com/hughwang10/jupyterlab-docker.git'
    #     dest: /home/vagrant/project