---
- name: afg
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: create project
      file:
        path: /home/vagrant/project
        owner: vagrant
        group: vagrant
        state: directory
        mode: 0755

    - name: Creates /etc/ansible
      become: yes
      file:
        path: /etc/ansible
        state: directory
        mode: 0755

    - name: Download ansible.cfg
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/ansible/ansible/devel/examples/ansible.cfg
        dest: /etc/ansible/ansible.cfg
        mode: 0644

    - name: update ansible.cfg
      become: yes
      lineinfile:
        dest: /etc/ansible/ansible.cfg
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^#host_key_checking.*', line: 'host_key_checking = False' }
        - { regexp: '^#pipelining.*', line: 'pipelining = False' }
        - { regexp: '^#forks.*', line: 'forks = 100' }
        - { regexp: '^#retry_files_enabled.*', line: 'retry_files_enabled = False' }

    - name: add apt key
      become: yes
      apt_key:
        url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
        state: present

    - name: add apt repo
      become: yes
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: install kubectl
      become: yes
      apt:
        name:
          - kubectl
        update_cache: yes

    - name: download minikube
      become: yes
      get_url:
        url: https://storage.googleapis.com/minikube/releases/v0.28.0/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: 0755

    - name: start minikube
      become: yes
      command: /usr/local/bin/minikube start --vm-driver=none
      register: rst
    - debug: msg="{{rst.stdout_lines}}"

    - name: add line for registry-afglab
      become: tyes
      lineinfile:
        path: /etc/hosts
        line: '10.44.147.246 registry-afglab'

    - name: upload CA cert
      copy:
        src: registry.crt
        dest: /usr/local/share/ca-certificates/registry.crt
        mode: 0644

    - name: load new CA
      become: yes
      shell: update-ca-certificates

    - name: restart docker
      become: yes
      service:
        name: docker
        state: restarted

    - name: apply registry-afglab secret
      become: yes
      shell: kubectl apply -f /vagrant/secret.yaml

    # - name: run hello-minikube
    #   become: yes
    #   shell: "{{item}}"
    #   with_items:
    #     - kubectl run hello-minikube --image=k8s.gcr.io/echoserver:1.10 --port=8080
    #     - kubectl expose deployment hello-minikube --type=NodePort
    #     - curl $(minikube service hello-minikube --url)
    #     - kubectl delete services hello-minikube
    #     - kubectl delete deployment hello-minikube
    #   register: rst
    # - debug: msg="{{rst.results[2].stdout_lines}}"

    # - name: clone jupyterlab-docker from github
    #   git:
    #     repo: 'https://github.com/hughwang10/jupyterlab-docker.git'
    #     dest: /home/vagrant/project/jupyter/

    # - name: clone flask-docker from github
    #   git:
    #     repo: 'https://github.com/hughwang10/flask-docker.git'
    #     dest: /home/vagrant/project/flask-docker/

    # - name: build flask-docker local image
    #   become: yes
    #   shell: docker build -t test .
    #   args:
    #     chdir: /home/vagrant/project/flask-docker/lifegame
    #   register: rst
    # - debug: msg="{{rst.stdout_lines}}"

    # - name: deploy flask-docker
    #   become: yes
    #   shell: kubectl apply -f /vagrant/deploy.yml

    # - name: run flask-docker
    #   become: yes
    #   shell: "{{item}}"
    #   with_items:
    #     - kubectl run flask-docker --image=flask-docker_flask-lifegame:latest --port=10080
    #     - kubectl expose deployment flask-docker --type=NodePort